spring:
  application:
    name: board
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui/index.html
    disable-swagger-default-url: true

server:
  port: 8082